apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: external-secrets-operator
  namespace: {{ include "eso-deployment-resources.namespace" . }}
  labels:
    operators.coreos.com/external-secrets-operator.{{ include "eso-deployment-resources.namespace" . }}: ''
    {{- include "eso-deployment-resources.labels" . | nindent 4 }}
spec:
  channel: stable
  installPlanApproval: {{ .Values.operator.installPlanApproval }}
  name: external-secrets-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.operator.version }}

