kind: Secret
apiVersion: v1
metadata:
  name: aws-access-secret
  namespace: {{ include "eso-sync-resources.namespace" . }}
  labels:
    {{- include "eso-sync-resources.labels" . | nindent 4 }}
stringData:
  access-key: {{ .Values.provider.aws.accessKey }}
  secret-access-key: {{ .Values.provider.aws.secretAccessKey }}
type: Opaque
