apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: eso-secret-store
  namespace: {{ include "eso-sync-resources.namespace" . }}
  labels:
    {{- include "eso-sync-resources.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: access-key
            name: aws-access-secret
          secretAccessKeySecretRef:
            key: secret-access-key
            name: aws-access-secret
      region: {{ .Values.provider.aws.region }}
      service: SecretsManager

