{{- range $appItem := .Values.provider.aws.externalSecret.apps }}
{{ if $appItem.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .localSecretName }}
  namespace: {{ include "eso-sync-resources.namespace" $ }}
  labels:
    project: {{ $appItem.project }}
    application: {{ $appItem.name }}
    {{- include "eso-sync-resources.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $appItem.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: eso-secret-store
  data:
  {{- range $keySet := $appItem.keySets }}
  - secretKey: {{ $keySet.templateKey }}
    remoteRef:
      key: {{ $appItem.remoteSecretBucket }}
      property: {{ $keySet.remoteKey }}
  {{- end }}
  target:
    name: {{ $appItem.localSecretName }}
    creationPolicy: "Owner"
    deletionPolicy: "Retain"
    template:
      type: {{ $appItem.secretType }}
      metadata:
        labels:
          application: {{ $appItem.name }}
          application.group: {{ $appItem.project }}
          {{- include "eso-sync-resources.labels" $ | nindent 10 }}
      data:
      {{- range $keySet := $appItem.keySets }}
        {{ $keySet.remoteKey }}: |- 
          {{ printf "%s .%s %s" "{{" $keySet.templateKey "| nospace | b64dec }}" }}
      {{- end }}
---
{{ end }}
{{- end }}