apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: eso
  namespace: {{ include "eso-sync-resources.namespace" . }}
  labels:
    {{- include "eso-sync-resources.labels" . | nindent 4}}
spec:
  webhook:
    create: false
  crds:
    createClusterExternalSecret: false
    createClusterSecretStore: false
  certController:
    create: false
  # this must be set to false when using olm
  installCRDs: false
  # Default values copied from <project_dir>/helm-charts/external-secrets/values.yaml
  replicaCount: 1
  image:
    repository: {{ .Values.operatorConfig.image.repository }}
    pullPolicy: {{ .Values.operatorConfig.image.pullPolicy }}
    tag: {{ .Values.operatorConfig.tag | default "" }}
  prometheus:
    enabled: false
    service:
      port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi 