apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "eso-deployment-resources.namespace" . }}
  name: external-secrets-operator-controller-manager
  labels:
    {{- include "eso-deployment-resources.labels" . | nindent 4}}
